<a href="https://colab.research.google.com/github/AnastasiaButus/Interpolation-of-logging-curves/blob/main/Super_function_seism_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1.1,2.9])
np.round(a)

array([1., 3.])

In [ ]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
def seism_vectors(main_array,
                  x_coord, y_coord,
                  z_top, z_bottom,
                  t_top, t_bottom,
                  delta_t=2,
                  index_top=900, index_bottom=1300):

    """ This function recieves seisma data, x+y coordinates of well`s
    and some constants. Returns array of seisma and it`s coordinates.

    main_array - 3D np.array of seisma
    x_coord - vector of x coordinates in meters of well`s
    y_coord - vector of y coordinates in meters of well`s
    z_top, z_bottom - bounds of krovla+podoshva in meters
    t_top, t_bottom - bounds of krovla+podoshva in mseconds
    delta_t - discretisation step of seisma in seconds
    index_top, index_bottom - indexes of cutting seisma cube
    """
    # Getting indexes for seism from coordinates
    x_index = np.round( (np.array(x_coord)-524272.72)/(9630.30/392) )
    y_index = np.round( (np.array(y_coord)-6410041.47)/((18876.79/768)) )

    # Getting seism data
    result_matrix = main_array[x_index, y_index, :]

    # Getting massive of depth values. Suggesting velocity=const.
    t = np.linspace(index_top*delta_t, (index_bottom-1)*delta_t, main_array.shape[2])
    z = (t - t_top)/(t_bottom-t_top)*(z_top-z_bottom) + z_top


    return result_matrix, z

In [ ]:
main_array = np.array([
    [[1, 11], [2,22], [3,33], [4,44]],
    [[5,55], [6,66], [7,77], [8,88]],
    [[9,99], [10,101], [11,111], [12,122]]
     ])

x_slice = [0, 1, 2, 2]

y_slice = [0, 1, 2, 3]

index_try = [100,200]

In [ ]:
result = seism_vectors(main_array, x_slice, y_slice, index_try)
print(result)

[[  1  11]
 [  6  66]
 [ 11 111]
 [ 12 122]]


In [ ]:
main_array[[0,1],[0,1],:]

array([[ 1, 11],
       [ 6, 66]])