In [2]:
import numpy as np
import pandas as pd


from func_slicing import slice_1d, slice_2d

In [3]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
y = np.array([0,11,22,33,44,55,66,77,88,99])
x_wind = 3

slice_1d(x, y, x_wind)

(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]]),
 array([11, 22, 33, 44, 55, 66, 77, 88]))

In [4]:
x = np.array([0,1,2,3,3.5])
y = np.array([0,11,22,33,333])
x_wind = 3

x_sl, y_sl = slice_1d(x, y, x_wind)
x_sl, y_sl

(array([[0. , 1. , 2. ],
        [1. , 2. , 3. ],
        [2. , 3. , 3.5]]),
 array([11, 22, 33]))

In [5]:
m_x = [[0,1,2,3,3.5],[4,5,6],[7,8,9]]
m_y = [[0,11,22,33,333],[44,55,66],[77,88,99]]

m_x_sl, m_y_sl = slice_2d(m_x, m_y, x_wind=3)
m_x_sl, m_y_sl

(array([[0. , 1. , 2. ],
        [1. , 2. , 3. ],
        [2. , 3. , 3.5],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]),
 array([11, 22, 33, 55, 88]))

## Теперь на реальных данных:

In [13]:
PATH_TO_SEISM = "../Reindex_seism.csv"
PATH_TO_GIS = "../Reindex_GIS.xlsx"

df_seisma = pd.read_csv(PATH_TO_SEISM, sep=";")
df_seisma.set_index("Unnamed: 0", inplace=True)
df_seisma.index.name = "z"

df_gis = pd.read_excel(PATH_TO_GIS)
df_gis.set_index("Depth", inplace=True)
df_gis.index.name = "z"

In [14]:
df_seisma

g274  g276  g277  g278  g279  g280  g281  g282  g288  g291  ...  g551  \
z                                                                 ...         
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      g552  g553  g554  g555  g556  g557  g558  g559  g581  
z                                                           
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[933 rows x 133 columns]

In [15]:
df_gis

g274  g276  g277  g278  g279  g280  g281  g282  g288  g291  ...  g551  \
z                                                                 ...         
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      g552  g553  g554  g555  g556  g557  g558  g559  g581  
z                                                           
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[933 rows x 143 columns]

Поиск пересечения вышек

In [53]:
all_columns = sorted(list(set(df_seisma.columns) & set(df_gis.columns)))
df_seisma, df_gis = df_seisma[all_columns], df_gis[all_columns]

In [54]:
df_seisma

g274  g276  g277  g278  g279  g280  g281  g282  g288  g291  ...  g551  \
z                                                                 ...         
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      g552  g553  g554  g555  g556  g557  g558  g559  g581  
z                                                           
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[933 rows x 133 columns]

In [55]:
df_gis

g274  g276  g277  g278  g279  g280  g281  g282  g288  g291  ...  g551  \
z                                                                 ...         
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      g552  g553  g554  g555  g556  g557  g558  g559  g581  
z                                                           
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
8      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
12     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
16     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
3712   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3716   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3720   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3724   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3728   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[933 rows x 133 columns]

Подготовка для нарезки

In [56]:
x_to_slice = []
y_to_slice = []

for well_name in df_seisma.columns:
    x = df_seisma[well_name]
    y = df_gis[well_name]

    mask = (x!=0.0)*(y!=0)

    x_to_slice.append(x[mask].to_list())
    y_to_slice.append(y[mask].to_list())

In [57]:
i = -1
len(x_to_slice[i]), len(y_to_slice[i])

(42, 42)

Нарезка данных

In [58]:
x, y = slice_2d(x_to_slice, y_to_slice, x_wind=5)
x, y

(array([[ 0.51101482,  0.69885307, -0.41231184, -1.0243877 , -0.85709648],
        [ 0.69885307, -0.41231184, -1.0243877 , -0.85709648, -1.00505789],
        [-0.41231184, -1.0243877 , -0.85709648, -1.00505789, -1.33063063],
        ...,
        [-1.96782381,  2.95248899,  3.30330538, -0.71516077, -0.80250986],
        [ 2.95248899,  3.30330538, -0.71516077, -0.80250986, -2.84086579],
        [ 3.30330538, -0.71516077, -0.80250986, -2.84086579, -0.81064346]]),
 array([-0.02871699, -0.05409696, -0.04119036, ..., -0.01816172,
         0.01969497, -0.00258892]))

In [59]:
x.shape, y.shape # - это все данные для МО

((9885, 5), (9885,))