In [55]:
import numpy as np


from func_slicing import slice_1d, slice_2d

In [56]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
y = np.array([0,11,22,33,44,55,66,77,88,99])
x_wind = 3

slice_1d(x, y, x_wind)

(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]]),
 array([11, 22, 33, 44, 55, 66, 77, 88]))

In [58]:
m_x = [[0,1,2,3],[4,5,6],[7,8,9]]
m_y = [[0,11,22,33],[44,55,66],[77,88,99]]

slice_2d(m_x, m_y, x_wind=3)

(array([[0, 1, 2],
        [4, 5, 6],
        [7, 8, 9]]),
 array([11, 55, 88]))